/* Sauve Ketty — version compatibilite KettyBot / ancien WebView */
var DEFAULT_WORDS=['facteur','viarhona','ceramique','labyrinthe','baignade','palais','poire','rhone','lama','accrobranche','escargot','chevre','fruits','velo','randonner','vignoble'];
var GOOD=['Super !','Bonne réponse !','Cool !','Waouh !','Bravo !','C’est ça !','',''];
var BAD=['Mince.','Aïe.','Ouille.','Et non.','Oups !','',''];
var WORDS=loadWords(),word='',guessed={},wrong={},eliminated={},lives=10,hintUsed=false,previousWord='',idleTimers=[];
var music=document.getElementById('music');
var VOLUME_KEY='sauveKettyVolume';
var gameVolume=parseInt(localStorage.getItem(VOLUME_KEY)||'55',10); if(isNaN(gameVolume))gameVolume=55;
function byId(id){return document.getElementById(id)}
function all(sel){return document.querySelectorAll(sel)}
function addClass(el,c){if(el.classList)el.classList.add(c);else if((' '+el.className+' ').indexOf(' '+c+' ')<0)el.className+=' '+c}
function removeClass(el,c){if(el.classList)el.classList.remove(c);else el.className=(' '+el.className+' ').replace(' '+c+' ',' ').replace(/^\s+|\s+$/g,'')}
function has(obj,k){return obj[k]===true}
function applyGameVolume(v){gameVolume=Math.max(0,Math.min(100,Number(v)||0));try{localStorage.setItem(VOLUME_KEY,String(gameVolume))}catch(e){}var n=gameVolume/100;music.volume=n*0.45;var aud=all('audio');for(var i=0;i<aud.length;i++)if(aud[i]!==music)aud[i].volume=n}
function cleanWord(w){w=String(w||'').toLowerCase();var from='àáâäãåçèéêëìíîïñòóôöõùúûüýÿœ';var to='aaaaaaceeeeiiiinooooouuuuyyoe';for(var i=0;i<from.length;i++)w=w.split(from.charAt(i)).join(to.substr(i,from.charAt(i)==='œ'?2:1));return w.replace(/[^a-z]/g,'')}
function loadWords(){try{var saved=JSON.parse(localStorage.getItem('sauveKettyWords')||'null');if(saved&&saved.length){var r=[];for(var i=0;i<saved.length;i++){var x=cleanWord(saved[i]);if(x)r.push(x)}return r}}catch(e){}return DEFAULT_WORDS.slice(0)}
function show(id){var s=all('.screen');for(var i=0;i<s.length;i++)removeClass(s[i],'active');addClass(byId(id),'active')}
function safePlay(el){if(!el)return;try{el.pause();el.currentTime=0;var p=el.play();if(p&&typeof p.catch==='function')p.catch(function(){})}catch(e){}}
function play(id){safePlay(byId(id))}
function say(text){byId('pepperLine').innerHTML=text||'';if(!text)return;try{if(window.speechSynthesis&&window.SpeechSynthesisUtterance){window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=1.03;u.pitch=1.08;window.speechSynthesis.speak(u)}}catch(e){}}
function random(arr){return arr[Math.floor(Math.random()*arr.length)]}
function chooseWord(){var pool=[];for(var i=0;i<WORDS.length;i++)if(WORDS[i]!==previousWord)pool.push(WORDS[i]);word=random(pool.length?pool:WORDS);previousWord=word}
function clearIdle(){for(var i=0;i<idleTimers.length;i++)clearTimeout(idleTimers[i]);idleTimers=[]}
function resetIdle(){clearIdle();idleTimers.push(setTimeout(function(){say(random(['Clique sur une lettre pour trouver le mot.','N’aie pas peur, tu peux cliquer sur une lettre.','Il reste encore quelques lettres à deviner !']))},30000));idleTimers.push(setTimeout(function(){say('Et bah alors ! J’ai besoin de ton aide ! Clique sur le clavier, pour choisir une lettre.');play('sfxTimer')},45000));idleTimers.push(setTimeout(function(){say('Je me sens un peu seul. Tant pis, on jouera une prochaine fois ! Bye bye.');setTimeout(home,4500)},55000))}
function unlockAudio(){var aud=all('audio');for(var i=0;i<aud.length;i++){try{aud[i].load()}catch(e){}}}
function startGame(){unlockAudio();chooseWord();guessed={};wrong={};eliminated={};lives=10;hintUsed=false;show('game');try{music.currentTime=0}catch(e){}safePlay(music);render();say('Bienvenue dans Sauve Ketty. Oulala, il m’arrive un truc. Pour réparer mon système, il faut retrouver un mot de passe. Mais je ne vois plus rien ! J’ai besoin de ton aide !');resetIdle()}
function render(){renderWord();renderKeyboard();byId('batteryImg').src='battery/'+(lives===0?'00':String(lives*10))+'.png';var hb=byId('hintBtn');if(hintUsed)addClass(hb,'used');else removeClass(hb,'used');hb.getElementsByTagName('img')[0].src=hintUsed?'buttons/hint_done.png':'buttons/hint.png'}
function renderWord(){var box=byId('word');box.innerHTML='';for(var i=0;i<word.length;i++){var ch=word.charAt(i),slot=document.createElement('div');slot.className='letter-slot';if(has(guessed,ch))slot.innerHTML='<div class="letter">'+ch.toUpperCase()+'</div><img class="underline" src="underline_yes.png">';else slot.innerHTML='<img class="blur" src="letter_blur.png"><img class="underline" src="underline_no.png">';box.appendChild(slot)}}
function renderKeyboard(){var kb=byId('keyboard');kb.innerHTML='';var rows=['ABCDEFGHIJ','KLMNOPQRS','TUVWXYZ'];for(var r=0;r<rows.length;r++){var row=document.createElement('div');row.className='key-row';for(var i=0;i<rows[r].length;i++){(function(L){var l=L.toLowerCase(),b=document.createElement('button'),path='keyboard/normal/'+L+'.png';b.className='key';if(has(guessed,l))path='keyboard/right/'+L+'-right.png';if(has(wrong,l)||has(eliminated,l))path='keyboard/false/'+L+'-false.png';if(has(eliminated,l))addClass(b,'disabled');b.innerHTML='<img src="'+path+'" alt="'+L+'">';b.disabled=has(guessed,l)||has(wrong,l)||has(eliminated,l);b.onclick=function(){pick(l)};row.appendChild(b)})(rows[r].charAt(i))}kb.appendChild(row)}}
function allWordGuessed(){for(var i=0;i<word.length;i++)if(!has(guessed,word.charAt(i)))return false;return true}
function pick(letter){resetIdle();if(word.indexOf(letter)>=0){guessed[letter]=true;play('sfxGood');say(random(GOOD));render();if(allWordGuessed())setTimeout(function(){finish(true)},700)}else{wrong[letter]=true;lives=Math.max(0,lives-1);play('sfxLife');say(random(BAD));render();if(lives===1)setTimeout(function(){say('Attention, dernière chance pour me sauver !')},500);if(lives===0)setTimeout(function(){finish(false)},700)}}
function finish(win){clearIdle();try{music.pause()}catch(e){}show('end');var img=byId('endImage');img.style.opacity='0';img.style.webkitTransform='scale(.88)';img.style.transform='scale(.88)';img.src=win?'sauve_ketty_win_kettybot.jpg':'sauve_ketty_lose_kettybot.jpg';byId('endText').innerHTML=win?'Bravo ! Tu as trouvé le bon mot ! Ketty est réparée !':'Le mot à trouver était « '+word.toUpperCase()+' ». Heureusement, Ketty est incassable !';setTimeout(function(){img.style.opacity='1';img.style.webkitTransform='scale(1)';img.style.transform='scale(1)'},80);if(win){play('sfxWin');setTimeout(function(){say('Bravo ! Tu as trouvé le bon mot ! Je suis complètement réparée ! Merci.')},300)}else{play('sfxLose');setTimeout(function(){say('Ouf ! Heureusement que je suis incassable ! Le mot à trouver était '+word+'.')},300)}}
function closeModal(){addClass(byId('modal'),'hidden')}
function modal(title,text,yesFn){byId('modalTitle').innerHTML=title;byId('modalText').innerHTML=text;var a=byId('modalActions');a.innerHTML='';var no=document.createElement('button');no.innerHTML='NON';no.onclick=closeModal;a.appendChild(no);if(yesFn){var yes=document.createElement('button');yes.innerHTML='OUI';yes.onclick=function(){yesFn();closeModal()};a.appendChild(yes)}removeClass(byId('modal'),'hidden')}
function useHint(){resetIdle();if(hintUsed){say('Tu as déjà utilisé ton indice.');return}play('sfxHint');modal('Indice','Attention, tu n’as droit qu’à un seul indice. Veux-tu vraiment l’utiliser maintenant ?',function(){hintUsed=true;play('sfxLife');say('Et hop, je vais t’enlever quelques mauvaises lettres !');var c=[],alpha='abcdefghijklmnopqrstuvwxyz';for(var i=0;i<alpha.length;i++){var x=alpha.charAt(i);if(word.indexOf(x)<0&&!has(guessed,x)&&!has(wrong,x))c.push(x)}for(var j=0;j<3&&c.length;j++){var k=Math.floor(Math.random()*c.length);eliminated[c.splice(k,1)[0]]=true}render()})}
function quit(){resetIdle();modal('Quitter','Es-tu sûr de vouloir quitter le jeu ?',function(){play('sfxQuit');say('Ok. Une autre fois peut-être.');setTimeout(home,1800)})}
function rules(){byId('modalTitle').innerHTML='Règles';byId('modalText').innerHTML='Trouve les bonnes lettres pour afficher le bon mot. Une mauvaise lettre fait baisser la batterie. Tu as 10 vies et un seul indice, qui élimine trois mauvaises lettres.';var a=byId('modalActions');a.innerHTML='';var b=document.createElement('button');b.innerHTML='J’AI COMPRIS';b.onclick=closeModal;a.appendChild(b);removeClass(byId('modal'),'hidden')}
function home(){clearIdle();try{music.pause()}catch(e){}try{if(window.speechSynthesis)window.speechSynthesis.cancel()}catch(e){}show('intro');byId('pepperLine').innerHTML=''}
byId('startBtn').onclick=startGame;byId('rulesBtn').onclick=rules;byId('hintBtn').onclick=useHint;byId('quitBtn').onclick=quit;byId('againBtn').onclick=startGame;byId('homeBtn').onclick=home;
applyGameVolume(gameVolume);
